export const HOME_HERO_TOKENS = {
  BORDER_RADIUS: 18,
  PADDING_HORIZONTAL: 14,
  PADDING_VERTICAL: 16,
  DOCK_PADDING_BOTTOM: 42
};

export const PROFILE_HERO_TOKENS = {
  HEIGHT: 68,
  BORDER_RADIUS: 14,
  PADDING_HORIZONTAL: 14,
  ICON_WRAP: 36,
  ICON_SIZE: 22,
  TITLE_FONT_SIZE: 11,
  SUBTITLE_FONT_SIZE: 16
};
